package com.dev.freya.model;

public enum ArtSupport {

	PAINTING_LINEN_CANVAS,
	PAINTING_COTTON_CANVAS,
	PAINTING_PAPER,
	PAINTING_CARDBOARD,
	PAINTING_WOOD,
	
	SCULPTURE_WAX,
	SCULPTURE_CLAY,
	SCULPTURE_PLATILINE,
	SCULPTURE_CARDBOARD_PASTE,
	SCULPTURE_PLASTER,
	SCULPTURE_STUCCO,
	SCULPTURE_STAFF,
	SCULPTURE_CEMENT,
	SCULPTURE_STONE,
	SCULPTURE_WOOD
	
	// TODO complete list with remaining drawing and photography supports
}
